# build manifest for travis-ci.com

language: c

addons:
  apt:
    packages:
      - libhdf5-dev

matrix:
  include:
    - os: linux
    - os: osx

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        make -C src CFLAGS="-O3 -march=native" LDLIBS="-lm -lhdf5"
    else
        make -C src
    fi
